### ISSUE TITLE
TypeError: argument of type 'module' is not iterable

### ISSUE THREAD

**Issue by coreybrett** [berniey/html5print#3]
I'm getting "TypeError: argument of type 'module' is not iterable" when trying to run this code.
http://pastebin.com/mvx4kYyL

**Comment by berniey** [comment]
The error message suggest issue resulted from installation issues.  I've just try the code from the URL and did not see the error.  Could you please do the following:
    - Including the full stack trace
    - Are you running from windows?

**Comment by coreybrett** [comment]
http://pastebin.com/WvNJWkie

Running on Debian 8 inside virtualenv.

**Comment by berniey** [comment]
Thanks Corey!  There is an incompatibilities issue with the underlying libraries.  Before the issue is fix please downgrade the following library in the mean time:

    pip install ply==3.4

**Comment by berniey** [comment]
Temporary fixing the issue by using ply version 3.4
