### ISSUE TITLE
Failed install on debian 8

### ISSUE THREAD

**Issue by johnsmeeth** [berniey/html5print#6]
I am install html5print but occur an error as below 
"pip install html5print
Collecting html5print
  Using cached html5print-0.1.1.tar.gz
Collecting beautifulsoup4>=4.3.2 (from html5print)
  Using cached beautifulsoup4-4.4.1-py3-none-any.whl
Collecting chardet>=2.2.1 (from html5print)
  Using cached chardet-2.3.0.tar.gz
Collecting html5lib>=0.999 (from html5print)
  Using cached html5lib-0.9999999.tar.gz
Collecting requests>=2.3.5 (from html5print)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting slimit>=0.8.1 (from html5print)
  Using cached slimit-0.8.1.zip
Collecting tinycss2>=0.4 (from html5print)
  Using cached tinycss2-0.5.tar.gz
Collecting ply==3.4 (from html5print)
  Using cached ply-3.4.tar.gz
Requirement already satisfied (use --upgrade to upgrade): six in ./v3env/lib/python3.4/site-packages (from html5lib>=0.999->html5print)
Collecting webencodings>=0.4 (from tinycss2>=0.4->html5print)
  Using cached webencodings-0.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dha2bzr1/webencodings/setup.py", line 8, in <module>
        ).read().strip()).group(1)
      File "/opt/projects/v3env/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1663: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dha2bzr1/webencodings/
"

Please tell me how to fix? Thanks

**Comment by berniey** [comment]
Just tried on debian/jessie64 (8.4) and it cannot reproduce the error.  The problem might be with ply.  Use ply 3.4 only.

You can test it by uninstalling webencoding and ply and install again.

    pip uninstall webencodings and ply
